---
- name: reload NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: reloaded

- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  changed_when: false
